version: "3"
services: 
  fastify-demo:
    image: "registry.github.com/kongnakornna/fastify_template_mysql"
    container_name: "fastify-demo"
    ports: 
      - 8001:8080

    volumes: 
      - config.conf:/home/api/config.conf

      